/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.text.NumberFormat;
/**
 *
 * @author thesmashburn
 */
public class MainFrame extends javax.swing.JFrame {
    public String addProductName;
    public int addProductId;
    public double addProductPrice;
    public String addProductVendor;
    public double addProductTax;
    public double addProductWeight;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        clearInputsCheckout();
        if (MarketPlaceDriver.mainSys.getUser() == null) {
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "card6");
        }
       // addAProductWarning.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        homeContainer = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        homeHeader = new javax.swing.JLabel();
        homeNoticeLabel = new javax.swing.JLabel();
        addContainer = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        updateContainer = new javax.swing.JPanel();
        submitButtonUpd = new javax.swing.JButton();
        backButtonUpd = new javax.swing.JButton();
        updateHeader = new javax.swing.JLabel();
        updateSearchField = new javax.swing.JTextField();
        updateFindLabel = new javax.swing.JLabel();
        updateSearchButton = new javax.swing.JButton();
        updateErrorLabel = new javax.swing.JLabel();
        updateWeightField = new javax.swing.JTextField();
        updatePriceField = new javax.swing.JTextField();
        updateVendorField = new javax.swing.JTextField();
        updateNameField = new javax.swing.JTextField();
        updateTaxField = new javax.swing.JTextField();
        updateNameLabel = new javax.swing.JLabel();
        updatePriceLabel = new javax.swing.JLabel();
        updateVendorLabel = new javax.swing.JLabel();
        updateTaxLabel = new javax.swing.JLabel();
        updateWeightLabel = new javax.swing.JLabel();
        checkoutContainer = new javax.swing.JPanel();
        submitButtonCheck = new javax.swing.JButton();
        backButtonCheck = new javax.swing.JButton();
        nameScroll = new javax.swing.JScrollPane();
        nameList = new javax.swing.JList<>();
        checkAddItem = new javax.swing.JLabel();
        checkProductIDLabel = new javax.swing.JLabel();
        checkQuantityLabel = new javax.swing.JLabel();
        checkHead = new javax.swing.JLabel();
        productIDField = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        checkName = new javax.swing.JLabel();
        checkQuantity = new javax.swing.JLabel();
        checkPrice = new javax.swing.JLabel();
        quantityScroll = new javax.swing.JScrollPane();
        quantityList = new javax.swing.JList<>();
        priceScroll = new javax.swing.JScrollPane();
        priceList = new javax.swing.JList<>();
        checkoutAddButton = new javax.swing.JButton();
        checkSubLabel = new javax.swing.JLabel();
        checkTotalLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        errorLabelCheckout = new javax.swing.JLabel();
        loginContainer = new javax.swing.JPanel();
        loginHeader = new javax.swing.JLabel();
        loginNameLabel = new javax.swing.JLabel();
        loginPassLabel = new javax.swing.JLabel();
        loginPassField = new javax.swing.JPasswordField();
        loginNameField = new javax.swing.JTextField();
        loginSubmitButton = new javax.swing.JButton();
        loginNoticeLabel = new javax.swing.JLabel();
        settingsContainer = new javax.swing.JPanel();
        settingsHeader = new javax.swing.JLabel();
        settingsProfileLabel = new javax.swing.JLabel();
        settingsPasswordLabel = new javax.swing.JLabel();
        settingsProfileField = new javax.swing.JTextField();
        settingsPasswordField = new javax.swing.JPasswordField();
        settingUpdateButton = new javax.swing.JButton();
        settingsBackButton = new javax.swing.JButton();
        settingsNoticeLabel = new javax.swing.JLabel();
        usersContainer = new javax.swing.JPanel();
        reportContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        addButton.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        addButton.setText("Add Product");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        checkoutButton.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        updateButton.setText("Update Product");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        homeHeader.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        homeHeader.setText("Welcome to MarketPlace!");

        homeNoticeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        javax.swing.GroupLayout homeContainerLayout = new javax.swing.GroupLayout(homeContainer);
        homeContainer.setLayout(homeContainerLayout);
        homeContainerLayout.setHorizontalGroup(
            homeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeContainerLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(homeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeContainerLayout.createSequentialGroup()
                        .addGap(0, 62, Short.MAX_VALUE)
                        .addComponent(homeHeader)
                        .addGap(109, 109, 109))
                    .addGroup(homeContainerLayout.createSequentialGroup()
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(homeContainerLayout.createSequentialGroup()
                .addGroup(homeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeContainerLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeContainerLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(homeNoticeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        homeContainerLayout.setVerticalGroup(
            homeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeContainerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(homeHeader)
                .addGap(88, 88, 88)
                .addGroup(homeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(homeNoticeLabel)
                .addGap(36, 36, 36))
        );

        mainPanel.add(homeContainer, "card3");

        submitButton.setText("Submit");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addContainerLayout = new javax.swing.GroupLayout(addContainer);
        addContainer.setLayout(addContainerLayout);
        addContainerLayout.setHorizontalGroup(
            addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContainerLayout.createSequentialGroup()
                .addContainerGap(623, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addGap(17, 17, 17))
        );
        addContainerLayout.setVerticalGroup(
            addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContainerLayout.createSequentialGroup()
                .addContainerGap(598, Short.MAX_VALUE)
                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(backButton))
                .addGap(20, 20, 20))
        );

        mainPanel.add(addContainer, "card2");

        submitButtonUpd.setText("Submit");
        submitButtonUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonUpdActionPerformed(evt);
            }
        });

        backButtonUpd.setText("Back");
        backButtonUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonUpdActionPerformed(evt);
            }
        });

        updateHeader.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        updateHeader.setText("Update Product");

        updateFindLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        updateFindLabel.setText("Find Product by ID:");

        updateSearchButton.setText("Search");
        updateSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSearchButtonActionPerformed(evt);
            }
        });

        updateErrorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        updateErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        updateNameLabel.setText("Name:");

        updatePriceLabel.setText("Price:");

        updateVendorLabel.setText("Vendor");

        updateTaxLabel.setText("Tax");

        updateWeightLabel.setText("Weight");

        javax.swing.GroupLayout updateContainerLayout = new javax.swing.GroupLayout(updateContainer);
        updateContainer.setLayout(updateContainerLayout);
        updateContainerLayout.setHorizontalGroup(
            updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateContainerLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(updateHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateContainerLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatePriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateVendorLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateContainerLayout.createSequentialGroup()
                            .addComponent(submitButtonUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(backButtonUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateContainerLayout.createSequentialGroup()
                            .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(updateContainerLayout.createSequentialGroup()
                                    .addComponent(updatePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateWeightLabel))
                                .addComponent(updateFindLabel)
                                .addGroup(updateContainerLayout.createSequentialGroup()
                                    .addComponent(updateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateTaxLabel)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(updateErrorLabel)
                                .addGroup(updateContainerLayout.createSequentialGroup()
                                    .addComponent(updateSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(updateSearchButton))
                                .addComponent(updateWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updateTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(125, 125, 125)))
                    .addComponent(updateVendorField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        updateContainerLayout.setVerticalGroup(
            updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateContainerLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(updateHeader)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateContainerLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(updateFindLabel))
                    .addGroup(updateContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateNameLabel)
                    .addComponent(updateTaxLabel))
                .addGap(34, 34, 34)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePriceLabel)
                    .addComponent(updateWeightLabel))
                .addGap(33, 33, 33)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateVendorField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateVendorLabel))
                .addGap(45, 45, 45)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButtonUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButtonUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        mainPanel.add(updateContainer, "card4");

        submitButtonCheck.setText("Finish");
        submitButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonCheckActionPerformed(evt);
            }
        });

        backButtonCheck.setText("Back");
        backButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonCheckActionPerformed(evt);
            }
        });

        nameList.setModel(new DefaultListModel());
        nameScroll.setViewportView(nameList);

        checkAddItem.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        checkAddItem.setText("Add an Item");

        checkProductIDLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        checkProductIDLabel.setText("Prodcut ID");

        checkQuantityLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        checkQuantityLabel.setText("Quantity");

        checkHead.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        checkHead.setText("Checkout");

        checkName.setText("Name");

        checkQuantity.setText("Quantity");

        checkPrice.setText("Price");

        quantityList.setModel(new DefaultListModel());
        quantityScroll.setViewportView(quantityList);

        priceList.setModel(new DefaultListModel());
        priceScroll.setViewportView(priceList);

        checkoutAddButton.setText("Add Item");
        checkoutAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutAddButtonActionPerformed(evt);
            }
        });

        checkSubLabel.setText("Sub-Total:");

        checkTotalLabel.setText("Total:");

        errorLabelCheckout.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout checkoutContainerLayout = new javax.swing.GroupLayout(checkoutContainer);
        checkoutContainer.setLayout(checkoutContainerLayout);
        checkoutContainerLayout.setHorizontalGroup(
            checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutContainerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkSubLabel)
                    .addComponent(checkTotalLabel))
                .addGap(29, 29, 29)
                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel)
                    .addComponent(subtotalLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(checkoutContainerLayout.createSequentialGroup()
                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkoutContainerLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(checkHead))
                    .addGroup(checkoutContainerLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(checkoutContainerLayout.createSequentialGroup()
                                .addComponent(checkName)
                                .addGap(63, 63, 63)
                                .addComponent(checkQuantity)
                                .addGap(18, 18, 18))
                            .addGroup(checkoutContainerLayout.createSequentialGroup()
                                .addComponent(nameScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantityScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGap(1, 1, 1)
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkoutContainerLayout.createSequentialGroup()
                                .addComponent(priceScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(checkoutContainerLayout.createSequentialGroup()
                                        .addGap(317, 317, 317)
                                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkProductIDLabel)
                                            .addComponent(checkQuantityLabel)
                                            .addComponent(submitButtonCheck))
                                        .addGap(18, 18, 18)
                                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(productIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                            .addComponent(quantityField)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(backButtonCheck))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkoutAddButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                                                .addComponent(errorLabelCheckout)
                                                .addGap(77, 77, 77))))))
                            .addGroup(checkoutContainerLayout.createSequentialGroup()
                                .addComponent(checkPrice)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkAddItem)))
                .addGap(50, 50, 50))
        );
        checkoutContainerLayout.setVerticalGroup(
            checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutContainerLayout.createSequentialGroup()
                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkoutContainerLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(checkHead)
                        .addGap(38, 38, 38)
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkName)
                            .addComponent(checkQuantity)
                            .addComponent(checkPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(checkoutContainerLayout.createSequentialGroup()
                                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkProductIDLabel)
                                    .addComponent(productIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkQuantityLabel)
                                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkoutAddButton)
                                .addGap(18, 18, 18)
                                .addComponent(errorLabelCheckout))
                            .addComponent(quantityScroll)
                            .addComponent(priceScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                            .addComponent(nameScroll)))
                    .addGroup(checkoutContainerLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(checkAddItem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkSubLabel)
                            .addComponent(subtotalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkTotalLabel)
                            .addComponent(totalLabel))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitButtonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButtonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );

        mainPanel.add(checkoutContainer, "card5");

        loginHeader.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        loginHeader.setText("MarketPlace Login");

        loginNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        loginNameLabel.setText("Username:");

        loginPassLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        loginPassLabel.setText("Password:");

        loginNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginNameFieldActionPerformed(evt);
            }
        });

        loginSubmitButton.setText("Submit");
        loginSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitButtonActionPerformed(evt);
            }
        });

        loginNoticeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        loginNoticeLabel.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout loginContainerLayout = new javax.swing.GroupLayout(loginContainer);
        loginContainer.setLayout(loginContainerLayout);
        loginContainerLayout.setHorizontalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContainerLayout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginContainerLayout.createSequentialGroup()
                        .addComponent(loginNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginHeader)
                    .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(loginSubmitButton)
                        .addGroup(loginContainerLayout.createSequentialGroup()
                            .addComponent(loginPassLabel)
                            .addGap(18, 18, 18)
                            .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(loginNoticeLabel)
                                .addComponent(loginPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(157, 157, 157))
        );
        loginContainerLayout.setVerticalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(loginHeader)
                .addGap(150, 150, 150)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginNameLabel)
                    .addComponent(loginNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginPassLabel)
                    .addComponent(loginPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(loginSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(loginNoticeLabel)
                .addGap(54, 54, 54))
        );

        mainPanel.add(loginContainer, "card6");

        settingsHeader.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        settingsHeader.setText("User Settings");

        settingsProfileLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        settingsProfileLabel.setText("Profile Picture URL:");

        settingsPasswordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        settingsPasswordLabel.setText("Password:");

        settingUpdateButton.setText("Update");

        settingsBackButton.setText("Back");

        settingsNoticeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        settingsNoticeLabel.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout settingsContainerLayout = new javax.swing.GroupLayout(settingsContainer);
        settingsContainer.setLayout(settingsContainerLayout);
        settingsContainerLayout.setHorizontalGroup(
            settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsContainerLayout.createSequentialGroup()
                .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(settingsContainerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsContainerLayout.createSequentialGroup()
                                .addComponent(settingsHeader)
                                .addGap(142, 142, 142))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsContainerLayout.createSequentialGroup()
                                .addComponent(settingUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(settingsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, settingsContainerLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(settingsContainerLayout.createSequentialGroup()
                                .addComponent(settingsPasswordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(settingsPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(settingsContainerLayout.createSequentialGroup()
                                .addComponent(settingsProfileLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(settingsProfileField, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(settingsNoticeLabel)
                .addGap(378, 378, 378))
        );
        settingsContainerLayout.setVerticalGroup(
            settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsContainerLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(settingsHeader)
                .addGap(118, 118, 118)
                .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsProfileLabel)
                    .addComponent(settingsProfileField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsPasswordLabel)
                    .addComponent(settingsPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(settingsNoticeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        mainPanel.add(settingsContainer, "card7");

        javax.swing.GroupLayout usersContainerLayout = new javax.swing.GroupLayout(usersContainer);
        usersContainer.setLayout(usersContainerLayout);
        usersContainerLayout.setHorizontalGroup(
            usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        usersContainerLayout.setVerticalGroup(
            usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );

        mainPanel.add(usersContainer, "card8");

        javax.swing.GroupLayout reportContainerLayout = new javax.swing.GroupLayout(reportContainer);
        reportContainer.setLayout(reportContainerLayout);
        reportContainerLayout.setHorizontalGroup(
            reportContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        reportContainerLayout.setVerticalGroup(
            reportContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );

        mainPanel.add(reportContainer, "card9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 821, 644);
    }// </editor-fold>//GEN-END:initComponents

     // Submit button -> add product
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
      /*  if (verifyNewProduct(productNameField.getText(), productIdField.getText(), productPriceField.getText(), productVendorField.getText(), productTaxField.getText(), productWeightField.getText())) {
            
            Boolean added = DataBaseManager.addProduct(addProductName, addProductId, addProductPrice, addProductVendor, addProductTax, addProductWeight);
            
            if (added) {
                CardLayout card = (CardLayout)mainPanel.getLayout();
                card.show(mainPanel, "card3");
                homeNoticeLabel.setText("Product succesfully added!");
                addInputsReset();
                MarketPlaceDriver.mainSys.updateLists();
            }
            
            else {
               CardLayout card = (CardLayout)mainPanel.getLayout();
               card.show(mainPanel, "card3");
                homeNoticeLabel.setText("Product failed to be added");
            }
            
            /*JDialog successDialog = new JDialog();
            successDialog.setTitle("Success");
            successDialog.setSize(200, 200);
        }
        else {  
            
            // Display warning
            return;
        }*/
    }//GEN-LAST:event_submitButtonActionPerformed
    
     /* THIS IS THE SECTION FOR EVENTS RELATED EVENTS*/
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card2");
    }//GEN-LAST:event_addButtonActionPerformed
    
     
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card3");
    }//GEN-LAST:event_backButtonActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        clearInputsCheckout();
        MarketPlaceDriver.mainSys.checkoutOrder();
        card.show(mainPanel, "card5");
    }//GEN-LAST:event_checkoutButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        changeInputsUpdate(false);
        card.show(mainPanel, "card4");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backButtonUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonUpdActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card3");
        
    }//GEN-LAST:event_backButtonUpdActionPerformed

    
    private void backButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonCheckActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card3");
    }//GEN-LAST:event_backButtonCheckActionPerformed

    /*This is the code for the checkout add item button*/
    private void checkoutAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutAddButtonActionPerformed
        // TODO add your handling code here:
        errorLabelCheckout.setText("");
        NumberFormat formatter = NumberFormat.getCurrencyInstance();
       
        if (!isInteger(productIDField.getText()) || !isInteger(quantityField.getText())) errorLabelCheckout.setText("*Fields must be Integers");
        else if (Integer.parseInt(quantityField.getText()) < 1) errorLabelCheckout.setText("*Quantity must be greater than 0");
        else {
            int productID = Integer.parseInt(productIDField.getText());
            int quantity = Integer.parseInt(quantityField.getText());
            CheckoutItem temp = MarketPlaceDriver.mainSys.addItemToCheckout(productID, quantity);
            if (temp.getID() != 0) {
                DefaultListModel nameModel = (DefaultListModel) nameList.getModel();
                DefaultListModel quanModel = (DefaultListModel) quantityList.getModel();
                DefaultListModel totalModel = (DefaultListModel) priceList.getModel();
                
                nameModel.addElement(temp.getName());
                quanModel.addElement(temp.getQuantity());
                totalModel.addElement(temp.getPrice());
                
                totalLabel.setText(formatter.format(MarketPlaceDriver.mainSys.getCurrentTotal()));
                subtotalLabel.setText(formatter.format(MarketPlaceDriver.mainSys.getCurrentSubTotal()));
            }
            else errorLabelCheckout.setText("*Product not found");
        }
        
    }//GEN-LAST:event_checkoutAddButtonActionPerformed

    private void submitButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonCheckActionPerformed
        // TODO add your handling code here:
        if (MarketPlaceDriver.mainSys.getCurrentCount() >= 1) {
            if (MarketPlaceDriver.mainSys.pushCurrentCheckoutOrder()) {
                CardLayout card = (CardLayout)mainPanel.getLayout();
                card.show(mainPanel, "card3");
                homeNoticeLabel.setText("Order sucessfully processed!");
                MarketPlaceDriver.mainSys.updateLists();
            }
            else errorLabelCheckout.setText("Problem connecting to server");
        }
        else errorLabelCheckout.setText("Must add items to cart");
    }//GEN-LAST:event_submitButtonCheckActionPerformed

    private void updateSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSearchButtonActionPerformed
        // TODO add your handling code here:
        updateErrorLabel.setText("");
        if (isInteger(updateSearchField.getText())) {
            int productID = Integer.parseInt(updateSearchField.getText());
            Product temp = MarketPlaceDriver.mainSys.findProductUpdate(productID);
            if (temp.getID() != 0) {
                updateNameField.setText(temp.getName());
                updatePriceField.setText(temp.getPrice() + "");
                updateVendorField.setText(temp.getVendor());
                updateTaxField.setText(temp.getTax() + "");
                updateWeightField.setText(temp.getWeight() + "");
                changeInputsUpdate(true);
            }
            else {
                updateErrorLabel.setText("*Product not found");
                changeInputsUpdate(false);
            }
        }
        else {
            updateErrorLabel.setText("*Invalid ID format");
            changeInputsUpdate(false);
        }
        
    }//GEN-LAST:event_updateSearchButtonActionPerformed

    private void submitButtonUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonUpdActionPerformed
        // TODO add your handling code here:
        Boolean priceBool = isDouble(updatePriceField.getText());
        Boolean taxBool = isDouble(updateTaxField.getText());
        Boolean weightBool = isDouble(updateWeightField.getText());
        Boolean nameBool = correctString(updateNameField.getText());
        Boolean vendorBool = correctString(updateVendorField.getText());
        if (!priceBool || !taxBool || !weightBool || !nameBool || !vendorBool) {
            updateErrorLabel.setText("*Incorrect format for given field(s)");
        }
        else {
            double price = Double.parseDouble(updatePriceField.getText());
            double tax = Double.parseDouble(updateTaxField.getText());
            double weight = Double.parseDouble(updateWeightField.getText());
            String name = updateNameField.getText();
            String vendor = updateVendorField.getText();
            
            if (MarketPlaceDriver.mainSys.pushProductUpdate(name, price, vendor, tax, weight)) {
                CardLayout card = (CardLayout)mainPanel.getLayout();
                card.show(mainPanel, "card3");
                homeNoticeLabel.setText("Product succesfully updated!");
            }
        }
        
    }//GEN-LAST:event_submitButtonUpdActionPerformed

    private void loginNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginNameFieldActionPerformed

    private void loginSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitButtonActionPerformed
        // TODO add your handling code here:
        String username = loginNameField.getText();
        char[] passwordChar = loginPassField.getPassword();
        String password = new String(passwordChar);
        
        if (MarketPlaceDriver.mainSys.authenticateUser(username, password)) {
             CardLayout card = (CardLayout)mainPanel.getLayout();
             card.show(mainPanel, "card3");
             
             if (!MarketPlaceDriver.mainSys.isAdmin()) {
                 //setvisibility
             }
             
             
        }
       
        
    }//GEN-LAST:event_loginSubmitButtonActionPerformed
    
    
     /* THIS IS THE SECTION FOR GENERAL METHODS */

    /*  public boolean verifyNewProduct(String nameIn, String idIn, String priceIn, String vendorIn, String taxIn, String weightIn) {
        
        try {
            addProductId = Integer.parseInt(idIn);
            addProductPrice = Double.parseDouble(priceIn);
            addProductTax = Double.parseDouble(taxIn);
            addProductWeight = Double.parseDouble(weightIn);
        } catch (NumberFormatException e) {
            addAProductWarning.setVisible(true);
            return false;
        }
        Product prod = MarketPlaceDriver.mainSys.findProductUpdate(addProductId);
        if (nameIn == null || idIn == null || priceIn == null || vendorIn == null || taxIn == null || weightIn == null) {
            addAProductWarning.setVisible(true);
            addAProductWarning.setText("* Re-evaluate fields");
            return false;
        }
        else if (prod.getID() != 0) {
            addAProductWarning.setVisible(true);
            addAProductWarning.setText("* Product with the ID already exists");
            return false;
        }
        
            addProductName = nameIn;
            addProductVendor = vendorIn;
            
        return true;
    }*/
    
    public Boolean isInteger(String str) {
        try {
        Integer.parseInt(str);
        return true;
    } catch (NumberFormatException nfe) {
        return false;
    } 
    }
    
    public Boolean isDouble(String str) {
        try {
        Double.parseDouble(str);
        return true;
    } catch (Exception nfe) {
        return false;
    } 
    }
    
    public Boolean correctString(String str) {
        try {
            if (str.trim().length() > 0) return true;
            else return false;
        } catch (Exception e) {
            return false;
        }
    }
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public void clearInputsCheckout() {
        nameList.setModel(new DefaultListModel());
        quantityList.setModel(new DefaultListModel());
        priceList.setModel(new DefaultListModel());
        subtotalLabel.setText("");
        totalLabel.setText("");
        productIDField.setText("");
        quantityField.setText("");
        homeNoticeLabel.setText("");
    }
    
    public void changeInputsUpdate(Boolean show) {
        homeNoticeLabel.setText("");
        updateNameField.setVisible(show);
        updateNameLabel.setVisible(show);
        updatePriceField.setVisible(show);
        updatePriceLabel.setVisible(show);
        updateVendorField.setVisible(show);
        updateVendorLabel.setVisible(show);
        updateTaxField.setVisible(show);
        updateTaxLabel.setVisible(show);
        updateWeightField.setVisible(show);
        updateWeightLabel.setVisible(show);
        if (!show) {
            updateNameField.setText("");
            updatePriceField.setText("");
            updateVendorField.setText("");
            updateTaxField.setText("");
            updateWeightField.setText("");
            updateSearchField.setText("");
        }
    }
    
   /* public void addInputsReset() {
        productIdField.setText("ID");
        productNameField.setText("Name");
        productPriceField.setText("Price");
        productVendorField.setText("Vendor");
        productWeightField.setText("Weight");
        productTaxField.setText("Tax");
        addAProductWarning.setVisible(false);
    }*/
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addContainer;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButtonCheck;
    private javax.swing.JButton backButtonUpd;
    private javax.swing.JLabel checkAddItem;
    private javax.swing.JLabel checkHead;
    private javax.swing.JLabel checkName;
    private javax.swing.JLabel checkPrice;
    private javax.swing.JLabel checkProductIDLabel;
    private javax.swing.JLabel checkQuantity;
    private javax.swing.JLabel checkQuantityLabel;
    private javax.swing.JLabel checkSubLabel;
    private javax.swing.JLabel checkTotalLabel;
    private javax.swing.JButton checkoutAddButton;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JPanel checkoutContainer;
    private javax.swing.JLabel errorLabelCheckout;
    private javax.swing.JPanel homeContainer;
    private javax.swing.JLabel homeHeader;
    private javax.swing.JLabel homeNoticeLabel;
    private javax.swing.JPanel loginContainer;
    private javax.swing.JLabel loginHeader;
    private javax.swing.JTextField loginNameField;
    private javax.swing.JLabel loginNameLabel;
    private javax.swing.JLabel loginNoticeLabel;
    private javax.swing.JPasswordField loginPassField;
    private javax.swing.JLabel loginPassLabel;
    private javax.swing.JButton loginSubmitButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JList<String> nameList;
    private javax.swing.JScrollPane nameScroll;
    private javax.swing.JList<String> priceList;
    private javax.swing.JScrollPane priceScroll;
    private javax.swing.JTextField productIDField;
    private javax.swing.JTextField quantityField;
    private javax.swing.JList<String> quantityList;
    private javax.swing.JScrollPane quantityScroll;
    private javax.swing.JPanel reportContainer;
    private javax.swing.JButton settingUpdateButton;
    private javax.swing.JButton settingsBackButton;
    private javax.swing.JPanel settingsContainer;
    private javax.swing.JLabel settingsHeader;
    private javax.swing.JLabel settingsNoticeLabel;
    private javax.swing.JPasswordField settingsPasswordField;
    private javax.swing.JLabel settingsPasswordLabel;
    private javax.swing.JTextField settingsProfileField;
    private javax.swing.JLabel settingsProfileLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton submitButtonCheck;
    private javax.swing.JButton submitButtonUpd;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JPanel updateContainer;
    private javax.swing.JLabel updateErrorLabel;
    private javax.swing.JLabel updateFindLabel;
    private javax.swing.JLabel updateHeader;
    private javax.swing.JTextField updateNameField;
    private javax.swing.JLabel updateNameLabel;
    private javax.swing.JTextField updatePriceField;
    private javax.swing.JLabel updatePriceLabel;
    private javax.swing.JButton updateSearchButton;
    private javax.swing.JTextField updateSearchField;
    private javax.swing.JTextField updateTaxField;
    private javax.swing.JLabel updateTaxLabel;
    private javax.swing.JTextField updateVendorField;
    private javax.swing.JLabel updateVendorLabel;
    private javax.swing.JTextField updateWeightField;
    private javax.swing.JLabel updateWeightLabel;
    private javax.swing.JPanel usersContainer;
    // End of variables declaration//GEN-END:variables
}
